import crypto from "node:crypto";
import { query } from "../services/db.js";
import { authenticateRequest } from "./auth.js";
const STATE_COOKIE = "bgp_github_state";
const keyText = () => process.env.GITHUB_TOKEN_ENCRYPTION_KEY || "";
function key(){ const raw=keyText(); const b=Buffer.from(raw,"base64"); if(b.length!==32) throw new Error("GITHUB_TOKEN_ENCRYPTION_KEY must be a base64-encoded 32-byte key."); return b; }
function sign(value){ const secret=process.env.AUTH_SESSION_SECRET||""; if(secret.length<32) throw new Error("AUTH_SESSION_SECRET must be set to at least 32 characters."); return crypto.createHmac("sha256",secret).update(value).digest("base64url"); }
function encrypt(value){ const iv=crypto.randomBytes(12), cipher=crypto.createCipheriv("aes-256-gcm",key(),iv); const data=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]); return [iv.toString("base64url"),cipher.getAuthTag().toString("base64url"),data.toString("base64url")].join("."); }
function decrypt(value){ const [ivText,tagText,dataText]=String(value||"").split("."); if(!ivText||!tagText||!dataText) return null; const decipher=crypto.createDecipheriv("aes-256-gcm",key(),Buffer.from(ivText,"base64url")); decipher.setAuthTag(Buffer.from(tagText,"base64url")); return Buffer.concat([decipher.update(Buffer.from(dataText,"base64url")),decipher.final()]).toString("utf8"); }
function setStateCookie(res,value){ const secure=process.env.NODE_ENV==="production"?"; Secure":""; res.setHeader("Set-Cookie",STATE_COOKIE+"="+value+"; Path=/; HttpOnly; SameSite=Lax"+secure+"; Max-Age=600"); }
function clearStateCookie(res){ const secure=process.env.NODE_ENV==="production"?"; Secure":""; res.append("Set-Cookie",STATE_COOKIE+"=; Path=/; HttpOnly; SameSite=Lax"+secure+"; Max-Age=0"); }
function readState(req){ for(const p of String(req.headers.cookie||"").split(";")){const [k,...v]=p.trim().split("=");if(k===STATE_COOKIE)return v.join("=");} return null; }
export async function beginGitHubConnect(req,res){ const user=await authenticateRequest(req); if(!user) throw new Error("Authentication required."); if(!process.env.GITHUB_CLIENT_ID||!process.env.GITHUB_CLIENT_SECRET) throw new Error("GitHub OAuth is not configured."); const nonce=crypto.randomBytes(24).toString("base64url"); const payload=user.id+"."+nonce; setStateCookie(res,payload+"."+sign(payload)); const redirect=process.env.GITHUB_OAUTH_REDIRECT_URI||((process.env.APP_URL||"http://localhost:3000")+"/api/github/oauth/callback"); const url=new URL("https://github.com/login/oauth/authorize"); url.searchParams.set("client_id",process.env.GITHUB_CLIENT_ID); url.searchParams.set("redirect_uri",redirect); url.searchParams.set("scope","read:user user:email repo"); return url.toString(); }
export async function finishGitHubConnect(req,res){ const raw=readState(req); clearStateCookie(res); const parts=String(raw||"").split("."); if(parts.length!==3) throw new Error("Invalid GitHub OAuth state."); const [userId,nonce,sig]=parts; const payload=userId+"."+nonce; if(sig!==sign(payload)) throw new Error("Invalid GitHub OAuth state."); const user=await authenticateRequest(req); if(!user||user.id!==userId) throw new Error("GitHub connection session expired."); const code=String(req.query.code||""); if(!code) throw new Error("GitHub authorization code missing."); const redirect=process.env.GITHUB_OAUTH_REDIRECT_URI||((process.env.APP_URL||"http://localhost:3000")+"/api/github/oauth/callback"); const tokenResponse=await fetch("https://github.com/login/oauth/access_token",{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify({client_id:process.env.GITHUB_CLIENT_ID,client_secret:process.env.GITHUB_CLIENT_SECRET,code,redirect_uri:redirect})}); const tokenData=await tokenResponse.json(); if(!tokenResponse.ok||!tokenData.access_token) throw new Error("GitHub authorization failed."); const gh=await fetch("https://api.github.com/user",{headers:{"Accept":"application/vnd.github+json","Authorization":"Bearer "+tokenData.access_token,"X-GitHub-Api-Version":"2022-11-28"}}); const profile=await gh.json(); if(!gh.ok) throw new Error(profile.message||"Unable to read GitHub identity."); await query("INSERT INTO github_accounts (user_id,github_user_id,github_login,access_token_encrypted) VALUES ($1,$2,$3,$4) ON CONFLICT (user_id) DO UPDATE SET github_user_id=EXCLUDED.github_user_id,github_login=EXCLUDED.github_login,access_token_encrypted=EXCLUDED.access_token_encrypted,updated_at=now()",[user.id,profile.id,profile.login,encrypt(tokenData.access_token)]); return profile; }
export async function getGitHubAccessToken(userId){ const result=await query("SELECT access_token_encrypted FROM github_accounts WHERE user_id=$1",[userId]); const encrypted=result.rows[0]?.access_token_encrypted; return encrypted?decrypt(encrypted):null; }
export async function getGitHubIdentity(userId){ const result=await query("SELECT github_user_id,github_login,created_at,updated_at FROM github_accounts WHERE user_id=$1",[userId]); return result.rows[0]||null; }